/*
 * File: CategoryDAO.java
 * Description: Data access class for product category records
 * Author: Zach Christianson
 * Date Created: July 9, 2026
 * Last Updated: July 9, 2026
 */

package com.snowboardstorefront.dao;

import com.snowboardstorefront.model.Category;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Handles database operations for the category table
 */
@Repository
public class CategoryDAO {

    private final JdbcTemplate jdbcTemplate;

    /**
     * Initializes the CategoryDAO with the database helper object
     *
     * @param jdbcTemplate Spring database helper object
     */
    public CategoryDAO(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    /**
     * Gets all product categories
     *
     * @return list of all categories
     */
    public List<Category> findAllCategories() {

        // Updated to include description so admin pages can display and edit it
        String sql = """
                SELECT category_id, name AS category_name, description
                FROM category
                ORDER BY name
                """;

        return jdbcTemplate.query(sql, (resultSet, rowNum) -> {
            Category category = new Category(
                    resultSet.getInt("category_id"),
                    resultSet.getString("category_name")
            );
            category.setDescription(resultSet.getString("description"));
            return category;
        });
    }

    // Find a single category by ID - used to pre-fill the edit form
    public Category findCategoryById(int categoryId) {

        String sql = """
                SELECT category_id, name AS category_name, description
                FROM category
                WHERE category_id = ?
                """;

        try {
            return jdbcTemplate.queryForObject(sql, (resultSet, rowNum) -> {
                Category category = new Category(
                        resultSet.getInt("category_id"),
                        resultSet.getString("category_name")
                );
                category.setDescription(resultSet.getString("description"));
                return category;
            }, categoryId);
        } catch (Exception exception) {
            // Return null if no category is found for the given ID
            return null;
        }
    }

    // Insert a new category row into the category table
    public void addCategory(Category category) {

        // SQL inserts name and description - category_id is auto-generated by MySQL
        String sql = """
                INSERT INTO category (name, description)
                VALUES (?, ?)
                """;

        jdbcTemplate.update(sql, category.getCategoryName(), category.getDescription());
    }

    // Update the name and description of an existing category
    public void updateCategory(Category category) {

        // SQL updates the name and description for the matching category_id
        String sql = """
                UPDATE category
                SET name = ?, description = ?
                WHERE category_id = ?
                """;

        jdbcTemplate.update(sql, category.getCategoryName(), category.getDescription(), category.getCategoryId());
    }

    // Delete a category row from the category table by its ID
    public void deleteCategory(int categoryId) {

        // SQL deletes the single category row that matches the given category_id
        // Note: deleting a category that has products assigned to it will fail due to foreign key constraints
        String sql = "DELETE FROM category WHERE category_id = ?";

        jdbcTemplate.update(sql, categoryId);
    }
}
