/*
 * File: ProductDAO.java
 * Description: Data access class for product records
 * Author: Zach Christianson
 * Date Created: July 9, 2026
 * Last Updated: July 13, 2026
 */

package com.snowboardstorefront.dao;

import com.snowboardstorefront.model.Product;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Handles database operations for the product table
 */
@Repository
public class ProductDAO {

    private final JdbcTemplate jdbcTemplate;

    /**
     * Initializes the ProductDAO with the database helper object
     *
     * @param jdbcTemplate Spring database helper object
     */
    public ProductDAO(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    /**
     * Gets all products with their category names
     *
     * @return list of all products
     */
    public List<Product> findAllProducts() {
        String sql = """
                SELECT 
                    p.product_id,
                    p.category_id,
                    p.name AS product_name,
                    p.description,
                    p.price,
                    p.stock_quantity,
                    c.name AS category_name
                FROM product p
                JOIN category c ON p.category_id = c.category_id
                ORDER BY p.name
                """;

        return jdbcTemplate.query(sql, (resultSet, rowNum) -> new Product(
                resultSet.getInt("product_id"),
                resultSet.getInt("category_id"),
                resultSet.getString("product_name"),
                resultSet.getString("description"),
                resultSet.getBigDecimal("price"),
                resultSet.getInt("stock_quantity"),
                resultSet.getString("category_name")
        ));
    }

    /**
     * Gets all products that belong to a selected category
     *
     * @param categoryName category name selected by the user
     * @return list of products in the selected category
     */
    public List<Product> findProductsByCategory(String categoryName) {
        String sql = """
            SELECT 
                p.product_id,
                p.category_id,
                p.name AS product_name,
                p.description,
                p.price,
                p.stock_quantity,
                c.name AS category_name
            FROM product p
            JOIN category c ON p.category_id = c.category_id
            WHERE c.name = ?
            ORDER BY p.name
            """;

        return jdbcTemplate.query(sql, (resultSet, rowNum) -> new Product(
                resultSet.getInt("product_id"),
                resultSet.getInt("category_id"),
                resultSet.getString("product_name"),
                resultSet.getString("description"),
                resultSet.getBigDecimal("price"),
                resultSet.getInt("stock_quantity"),
                resultSet.getString("category_name")
        ), categoryName);
    }

    /**
     * Finds one product by its product ID
     *
     * @param productId product ID from the database
     * @return matching product, or null if no product is found
     */
    public Product findProductById(int productId) {
        String sql = """
                SELECT 
                    p.product_id,
                    p.category_id,
                    p.name AS product_name,
                    p.description,
                    p.price,
                    p.stock_quantity,
                    c.name AS category_name
                FROM product p
                JOIN category c ON p.category_id = c.category_id
                WHERE p.product_id = ?
                """;

        try {
            return jdbcTemplate.queryForObject(
                    sql,
                    (resultSet, rowNum) -> new Product(
                            resultSet.getInt("product_id"),
                            resultSet.getInt("category_id"),
                            resultSet.getString("product_name"),
                            resultSet.getString("description"),
                            resultSet.getBigDecimal("price"),
                            resultSet.getInt("stock_quantity"),
                            resultSet.getString("category_name")
                    ),
                    productId
            );
        } catch (Exception exception) {
            return null;
        }
    }

    // Insert a new product row into the product table
    public void addProduct(Product product) {

        // SQL inserts all fields except product_id which is auto-generated by MySQL
        String sql = """
                INSERT INTO product (category_id, name, description, price, stock_quantity)
                VALUES (?, ?, ?, ?, ?)
                """;

        jdbcTemplate.update(
                sql,
                product.getCategoryId(),
                product.getProductName(),
                product.getDescription(),
                product.getPrice(),
                product.getStockQuantity()
        );
    }

    // Update an existing product row using the product_id to find the correct row
    public void updateProduct(Product product) {

        // SQL updates every editable field for the product with the matching product_id
        String sql = """
                UPDATE product
                SET category_id = ?, name = ?, description = ?, price = ?, stock_quantity = ?
                WHERE product_id = ?
                """;

        jdbcTemplate.update(
                sql,
                product.getCategoryId(),
                product.getProductName(),
                product.getDescription(),
                product.getPrice(),
                product.getStockQuantity(),
                product.getProductId()
        );
    }

    // Delete a product row from the product table by its ID
    public void deleteProduct(int productId) {

        // SQL deletes the single product row that matches the given product_id
        String sql = "DELETE FROM product WHERE product_id = ?";

        jdbcTemplate.update(sql, productId);
    }
}
