spring.application.name=snowboard-storefront

spring.datasource.url=jdbc:mysql://localhost:3306/snowboard_storefront
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

